# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bc3e836fa8959ca95a92614c8593e53ae9d4d4f38c312dab927cd1667f37d831e4a0cddff086fd496253e63ccb5f892cbb6e20bef1a7a26390b228e09434eb56

test:
  secret_key_base: 613644394e15009338ef31e3fe13b5de2175bc6b160a0f2200d078657746aadc1d4d69041a758c15c9264492479304b0296d19a8a58c4eee001c56a92041a0d4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
